### ISSUE TITLE
Boost in The IAM cloud 

### ISSUE THREAD

**Issue by peskareta** [balmli/com.systemair#1]
I would like to have the boost mode option in the IAM as well. That would reduce the amount of flows needed for increase in fan speed. Thank you for the good work!!

**Comment by balmli** [comment]
Yes, thanks for the feedback.

But "Boost mode" is that just High in a predefined period ?

**Comment by peskareta** [comment]
Yes! Predefined in Systemair settings. Useful because once activated it
will revert to normal Auto mode when finished. Standard is 15min.

Thanks👍

lør. 4. apr. 2020 kl. 15:25 skrev Bjørnar Almli <notifications@github.com>:

**Comment by balmli** [comment]
Install v. 0.9.6.  

https://homey.app/no-no/app/com.systemair/Systemair/test/

You can comment and ask other users on the community pages:

https://community.athom.com/t/app-systemair/27862
